FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# QueryV

QueryV is api for querying items.

## Query [/api/v1/phone/]

### Query companies [GET]

+ Request (application/json)

        {
            "user": "example",
            "passwd": "secret",
            "query_string": "0404040404",
        }

+ Response 200 (application/json)

        [
            {
                "query_string": "0404040404",
                "result_count": "2",
                "result_list": [
                    {
                        "business_id": "01658672", 
                        "company_name": "Pertunmaan kunta", 
                        "link": "http://www.pertunmaa.fi", 
                        "industry_code_2": 84, 
                        "industry_code_5": 84110, 
                        "address": "Pertuntie 14", 
                        "postal": "19430", 
                        "city": "PERTUNMAA", 
                        "country": "FI", 
                        "technologies": [
                            "Softlayer.com", 
                            "Wordpress", 
                            "Hotmail.com", 
                            "Javascript", 
                            "Office365 email", 
                            "Facebook", 
                            "Csl.de", 
                            "Apache", 
                            "Fi", 
                            "Php", 
                            "Debian", 
                            "Jquery", 
                            "Outlook.com", 
                            "Google analytics", 
                            "Joker.com", 
                            "Www", 
                            "En", 
                            "Instagram", 
                            "Oma nimipalvelin", 
                            "Apache/2.4.10", 
                            "Google font api", 
                            "Io-tek.com"
                        ], 
                        "conclusions": []
                    }
                ]
            }
        ]


